### ISSUE TITLE
Not Working When Selecting The Same File Twice

### ISSUE THREAD

**Issue by blackbusters** [jburman/W8lessLabs.Blazor.LocalFiles#4]
I've tried that the first time when i select file "a.txt", it works, but after that when I tried calling select file again and select the same "a.txt" file, it won't do anything. And it works if I select another file like "b.txt".

Is there any way to select the same file twice?

**Comment by jburman** [comment]
Thanks for reporting this. It appears that some browsers won't re-fire the change event on file inputs when the path doesn't change.
Please give the new 0.9.1 package a try and let me know how that works for you.

**Comment by blackbusters** [comment]
Sorry for not describing that I'm using chrome for browser.

I just tried the new 0.9.1 package and it is working as expected.

Thanks for fixing this, really appreciate it.
